In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('final dataset.csv')

In [3]:
data = data.drop_duplicates()

In [4]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,5] = le.fit_transform(x[:,5])
x[:,7] = le.fit_transform(x[:,7])
x[:,12] = le.fit_transform(x[:,12])
x[:,13] = le.fit_transform(x[:,13])
y = le.fit_transform(y)

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [7]:
scaler = MinMaxScaler(feature_range=(0, 1))
x= scaler.fit_transform(x)

/home/turjoy/anaconda3/envs/Arafat/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
     x, y, test_size = 0.2, random_state = 100) 

In [9]:
from sklearn import svm
svm = svm.SVC(gamma='scale', decision_function_shape='ovo')
svm.fit(x_train, y_train)
prediction = svm.predict(x_test)
print(svm.score(x_test, y_test))


0.9865198006818778


In [10]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, prediction))

[[   359      0     21      0      0]
 [     5 187820     23      0      0]
 [     0     40    567      0      0]
 [     6    800     33    404      0]
 [     0   1899      0      0  17738]]


In [12]:
from sklearn.metrics import classification_report

In [14]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       0.97      0.94      0.96       380
           1       0.99      1.00      0.99    187848
           2       0.88      0.93      0.91       607
           3       1.00      0.33      0.49      1243
           4       1.00      0.90      0.95     19637

   micro avg       0.99      0.99      0.99    209715
   macro avg       0.97      0.82      0.86    209715
weighted avg       0.99      0.99      0.99    209715

